version: "3.9"

services:
  backend:
    build: ..
    container_name: ai_job_backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - ../uploads:/app/uploads
    env_file:
      - ../backend/.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: ai_job_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: jobs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: ai_job_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../frontend:/var/www/html
    depends_on:
      - backend

volumes:
  postgres_data:
